src/Web/ViewModels/HomeViewModel.cs
using System.Collections.Generic;
using Domain.Data.Respositories;
using Domain.Model;

namespace Web.ViewModels
{
    public class HomeViewModel
    {
        private readonly ISubjectRepository _subject;
        public ICollection<Subject> Subjects { get; set; }

        public HomeViewModel(ISubjectRepository subject)
        {
            _subject = subject;
            Subjects = _subject.GetAll();
        }
    }

}

src/Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data.EF5.Repositories;
using Domain.Data.Respositories;
using Domain.Model;
using Domain.Services;
using Web.ViewModels;

namespace Web.Controllers
{
    public class AboutController : Controller
    {
        private readonly IContactInfoRespository _contactInfoRespository;
        public AboutController()
        {
            _contactInfoRespository = new ContactInfoRepository();
        }
        [HttpGet]
        public ActionResult Index()
        {
            var model = new ContactViewModel
            {
                UserRequest = new ContactInfo()
            };
            return View(model); 
        }
        [HttpPost]
        public ActionResult Index(ContactInfo model, FormCollection form)
        {
            if (ModelState.IsValid && model != null)
            {
                model.CreateDate = DateTime.Now;
                _contactInfoRespository.Add(model);
                _contactInfoRespository.SaveChanges();
                var emailService = new NotificationService();
               if(! emailService.Send(new Notification{contactInfo = model}))
               {
                   //log some error 
               }
                return PartialView("Partial/UserContact");
            }
            return View(new ContactViewModel { UserRequest = model });
        }

    }
}

src/Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data.EF5.Repositories;
using Domain.Data.Respositories;
using Domain.Model;
using Web.ViewModels;


namespace Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        private readonly ISubjectRepository _subject;
        public HomeController()
        {
            _subject = new SubjectRepository();
        }

        public ActionResult Index()
        {
            
            return View(new HomeViewModel(_subject));
        }
    }
}

src/Web/Controllers/PastWorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data.EF5.Repositories;
using Domain.Data.Respositories;
using Domain.Model;
using Domain.Services;
using Web.ViewModels;


namespace Web.Controllers
{
    public class PastWorkController : Controller
    {
        //
        // GET: /PastWork/
        private readonly IPastWorkRepository _pastWorkRepository;
        public PastWorkController()
        {
            _pastWorkRepository = new PastWorkRepository();
        }

        public ActionResult Index()
        {
            return View(new PastSites(_pastWorkRepository));
        }
        [HttpPost]
        public JsonResult Index(string id)
        {
            return Json(new PastSiteDetail(_pastWorkRepository, id));
        }
    }
}

src/Web/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data.EF5.Repositories;
using Domain.Data.Respositories;
using Domain.Model;
using Domain.Services;
using Web.ViewModels;

namespace Web.Controllers
{
    public class SkillsController : Controller
    {
        private readonly ITopicRepository _topicRepository;
        private readonly IContactInfoRespository _contactInfoRespository;
        public SkillsController()
        {
            _contactInfoRespository = new ContactInfoRepository();
            _topicRepository = new TopicRepository();
        }

        public ActionResult FrontEnd()
        {
            return View(new TopicViewModel(_topicRepository, "5"));
        }

        public ActionResult WebApplications(string id)
        {
            return View(new TopicViewModel(_topicRepository, "6"));
        }

        //[HttpGet]
        //public ActionResult About()
        //{
        //    var model = new ContactViewModel
        //                    {
        //                        UserRequest = new ContactInfo()
        //                    };
        //    return View(model); 
        //}

        //[HttpPost]
        //public ActionResult About(ContactInfo model, FormCollection form)
        //{
        //    if (ModelState.IsValid && model != null)
        //    {
        //        _contactInfoRespository.Add(model);
        //        _contactInfoRespository.SaveChanges();
        //        return PartialView("Partial/UserContact");
        //    }
        //    return View(new ContactViewModel{UserRequest = model});
        //}
    }
}

src/Web/Views/Home/Index.cshtml
@model Web.ViewModels.HomeViewModel
@{
    ViewBag.Title = "Freelance Web Developer | jeffwrathall.com";
}
@*Refactor the panels into a for each with some conditions*@

<div id="HomeContent">
    <div class="PanelWrapper">
        <div class="PanelContent" style="height:600px;">
            <div style="padding-left:10px;">
                <div class="row">
                    <div class="span10">
                        <div style="border-top: dotted #bcbcbc 1px; width:100%; height:1px;padding-bottom:14px; width:95%;"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="span5">
                        <div class="Panel">
                            @{ 
                                var subjectItem = Model.Subjects.Take(1).Single(); 
                                <span class="PanelTitle"><a href="/Topics/@subjectItem.Url" >@subjectItem.Title</a></span>
                                <p>
                                    @subjectItem.Summary
                                </p>
                                <div style="padding:0 35px 8px 0; position:absolute; top:0;right:0;"><a href="@Url.Action(subjectItem.Url, "Skills")" class="next-detail"></a></div>
                            }

                        </div>
                    </div>
                    <div class="span5">
                        <div class="Panel">
                            @{
                                var subjectItem1 = Model.Subjects.Skip(1).Take(1).Single();
                                <span class="PanelTitle"><a href="/Topics/@subjectItem1.Url" >@subjectItem1.Title</a></span>
                                <p>
                                    @subjectItem1.Summary
                                </p>
                                 <div style="padding:0 35px 8px 0; position:absolute; top:0;right:0;"><a href="@Url.Action(subjectItem1.Url, "Skills")" class="next-detail"></a></div>
                            }   
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="span5">
                        <div style="border-top: dotted #bcbcbc 1px; width:100%; height:1px;padding-bottom:14px; width:90%;"></div>
                    </div>
                    <div class="span5">
                        <div style="border-top: dotted #bcbcbc 1px; width:100%; height:1px;padding-bottom:14px; width:90%;"></div>
                    </div>
                </div>
                <div class="row">
                    <div class="span5">
                        <div class="Panel">
                            @{ 
                                var subjectItem2 = Model.Subjects.Skip(2).Take(1).Single(); 
                                <span class="PanelTitle"><a href="@Url.Action("Index","About")" >@subjectItem2.Title</a></span>
                                <p>
                                    @subjectItem2.Summary
                                </p>
                                 <div style="padding:0 35px 8px 0; position:absolute; top:0;right:0;"><a href="@Url.Action("Index","About")" class="next-detail"></a></div>
                            }         
                        </div>
                    </div>
                    <div class="span5">
                        <div class="Panel">
                            @{ 
                                var subjectItem3 = Model.Subjects.Skip(3).Take(1).Single(); 
                                <span class="PanelTitle"><a href="@subjectItem3.Url" >@subjectItem3.Title</a></span>
                                <p>
                                    @subjectItem3.Summary
                                </p>
                                 <div style="padding:0 35px 8px 0; position:absolute; top:0;right:0;"><a href="@Url.Action("Index","PastWork")" class="next-detail"></a></div>
                            }    
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="span10">
                        <div style="border-top: dotted #bcbcbc 1px; width:100%; height:1px;padding-bottom:14px; width:95%;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>